name: nexo-dev

services:
  db:
    image: postgres:16-alpine
    container_name: nexo-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nexo
      - POSTGRES_PASSWORD=nexo
      - POSTGRES_DB=nexo
    ports:
      - "5432:5432"
    volumes:
      - nexo_db_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexo"]
      interval: 5s
      timeout: 4s
      retries: 5

  redis:
    image: redis:7.2.3-alpine
    container_name: nexo-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - nexo_redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 4s
      retries: 5

volumes:
  nexo_db_dev_data:
  nexo_redis_dev_data:

